spring:
  datasource:
    url: jdbc:mariadb://192.168.1.177:3306/loadtest
    username: root
    password: password
#    url: jdbc:mariadb://localhost:3306/loadtest
#    username: darass
#    password: local
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximumPoolSize: 3
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
