spring:
  datasource:
    url: jdbc:mariadb://192.168.1.177:3306/loadtest
    username: root
    password: password
#    url: jdbc:mariadb://localhost:3306/loadtest
#    username: darass
#    password: local
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
